### ISSUE TITLE
cant connect to database

### ISSUE THREAD

**Issue by mrwandii** [MonkeyD-Core/Simple-Cloud-Mining#4]
hello, can you kindly help out i've having some issues getting it to connect to my database 
i dont really know which of the files i should edit 
here is my error message https://snipboard.io/2FDySU.jpg
thanks

**Comment by mrwandii** [comment]
update! 
https://snipboard.io/OxYVyP.jpg still facing the same issue

**Comment by MonkeyD-Core** [comment]
It's clearly showing cant connect to your database, re-check your database
